[platformio]
extra_configs = variants/*/platformio.ini

[common]
lib_deps =
    ayushsharma82/ElegantOTA @ 4.0.0
    https://github.com/petrkr/log4mcu.git
    https://github.com/petrkr/PofoSmartCable.git

build_flags =
    -I variants/${PIOENV}
    #-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
