[platformio]
extra_configs = variants/*/platformio.ini

[common]
lib_deps =
    #https://github.com/ESP32Async/AsyncTCP.git#v3.3.8
    #https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.7.4
    #ayushsharma82/ElegantOTA @ 3.1.7

build_flags =
    -I variants/${PIOENV}
    #-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
