; PlatformIO Project Configuration File
[env:octopuslab-c3board]
board = esp32-c3-devkitm-1

build_flags =
	${common.build_flags}
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

lib_deps =
	${common.lib_deps}
